#ifndef KEYBOARD_IDENTITY_DEFAULTS_H
#define KEYBOARD_IDENTITY_DEFAULTS_H

#include <stdbool.h>

/* Official binaries use these values until an NVS override is saved. */
#define TYPX_IDENTITY_DEFAULT_DEVICE_NAME "Typxen Keyboard"
#define TYPX_IDENTITY_DEFAULT_MANUFACTURER "Typxen"
#define TYPX_IDENTITY_DEFAULT_MODEL "Typxen ESP32-CAM"
#define TYPX_IDENTITY_DEFAULT_HARDWARE_REVISION "1.0"
#define TYPX_IDENTITY_DEFAULT_SOFTWARE_REVISION "1.0.0"
#define TYPX_IDENTITY_DEFAULT_BATTERY_ENABLED true
#define TYPX_IDENTITY_DEFAULT_BATTERY_MINIMUM 50u
#define TYPX_IDENTITY_DEFAULT_BATTERY_MAXIMUM 90u
#define TYPX_IDENTITY_DEFAULT_BATTERY_CURRENT 90u
#define TYPX_IDENTITY_DEFAULT_BATTERY_INTERVAL_MINUTES 20u

/* 0xffff is reserved/unassigned, not another vendor's registered USB VID. */
#define TYPX_IDENTITY_NEUTRAL_PNP_VENDOR_ID 0xffffu
#define TYPX_IDENTITY_NEUTRAL_PNP_PRODUCT_ID 0x0001u
#define TYPX_IDENTITY_NEUTRAL_PNP_VERSION 0x0100u

#endif
